FROM ubuntu

RUN apt-get update
RUN apt-get install -y openjdk-8-jre

COPY ./target/spring-rest-app-1.0.jar /www/spring-rest-app-1.0.jar

ENTRYPOINT ["/usr/bin/java", "-jar", "-Dspring.profiles.active=default", "/www/spring-rest-app-1.0.jar"]